### ISSUE TITLE
Unable to find the inital admin password for the webui

### ISSUE THREAD

**Issue by adam248** [majewsky/portunus#28]
Hi,
I was just testing this out in NixOS and I am using `services.portunus.enable` etc...
I see that the initial password is printed to stdout only once but I did this with a `nixos-rebuild switch` command which runs Portunus as a system service.

I am hoping there is a way to still get the initial password or a simple way to set it myself.

Or should I delete and run it directly first, then enable the service?

**Comment by SuperSandro2000** [comment]
You can find the password in journald by running `journalctl -u portunus -e`. If it is no longer there, you need to delete the state directory ``/var/lib/portunus`` or you seed your admin user.

**Comment by adam248** [comment]
Thank you very much. Deleting the dir and re-running and then `journalctl` did the trick.
